// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://voccaxesfzawmscpthfe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZvY2NheGVzZnphd21zY3B0aGZlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ5NDM5ODIsImV4cCI6MjA1MDUxOTk4Mn0.L3JK1hi7sxT2ki_CucCgm3F0KHaRzHbIxUh5LsrG-Ms";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);